name: law_library
description: A modern law library app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🌍 Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  #Excel Reader
  csv: ^8.0.0
  excel: ^4.0.6

  # 🎨 UI & State
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^8.0.0
  flutter_svg: ^2.1.0
  flutter_slidable: ^4.0.0
  dropdown_search: ^7.0.0
  flutter_animate: ^4.2.3

  # 💾 Local Storage (Mobile / Desktop)
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0
  path: ^1.9.0
  connectivity_plus: ^7.0.0

  # 🌐 Network
  http: ^1.4.0
  crypto: ^3.0.6

  # 🖼 Media
  cached_network_image: ^3.4.1
  video_player: ^2.8.3

  # 🧪 Utils
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/payment.mp4

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  remove_alpha_ios: true
